# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('num_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('devuelto', models.BooleanField(default=False)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSGB.Ejemplar')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('documento', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('moroso', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSGB.Socio'),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSGB.Libro'),
        ),
    ]
